name: Deploy Apps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Prepare gh-pages directory
        run: mkdir -p gh-pages

      - name: Checkout existing gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Email App
        run: |
          cd examples/email
          npm install
          npm run build
          mkdir -p ../../gh-pages/email
          cp -R dist/* ../../gh-pages/email

      - name: Build Core Connection App
        run: |
          cd examples/core-connection
          npm install
          npm run build
          mkdir -p ../../gh-pages/core-connection
          cp -R dist/* ../../gh-pages/core-connection

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
